name: Scrape

on:
  schedule:
    - cron: '50 20 * * *'

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
      - name: Install requirements
        run: pip install -r req.txt
      - name: Run Scraper
        run: python scraper.py