name: Scrape

on:
  schedule:
    - cron: '0 21 * * *'
    - cron: '0 9 * * *'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2.0.0

      - name: Install requirements
        run: pip install -r req.txt
      
      - name: Run Scraper
        run: python scraper.py
      
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      
      - name: check for changes
        run: git status
      
      - name: stage changed files
        run: git add .
      
      - name: commit changed files
        run: git commit -m "Auto updating Data"
      
      - name: fetch from master
        run: git fetch origin master
      
      - name: push code to master
        run: git push origin master