name: VPN and Run Python Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup OpenVPN
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn
        echo "${{ secrets.OVPN_CONFIG }}" > config.ovpn
        # If your config requires auth, create a file with the credentials
        if [[ ! -z "${{ secrets.OVPN_USERNAME }}" && ! -z "${{ secrets.OVPN_PASSWORD }}" ]]; then
          echo "${{ secrets.OVPN_USERNAME }}" > vpnauth.txt
          echo "${{ secrets.OVPN_PASSWORD }}" >> vpnauth.txt
          sudo openvpn --config config.ovpn --auth-user-pass vpnauth.txt &
        else
          sudo openvpn --config config.ovpn &
        fi
        sleep 10  # Give VPN some time to establish
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt

    - name: Run Python script
      run: |
        python scrape.py
