name: Scrape

on: workflow_dispatch

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2.0.0

      - name: Install requirements
        run: pip install -r req.txt
      
      - name: Run Scraper
        run: python scraper.py
      
      - name: Set Git email
        run: git config --global user.email "aliyzd1379@gmail.com"

      - name: Set Git name
        run: git config --global user.name "Ali YZ"
        
      - name: remove origin
        run: git remote remove origin

      - name: add remote with Token
        run: git remote add origin https://${{ secrets.SECRET_TOKEN }}@github.com/myprogrammerpersonality/Flights_Delay.git
      
      - name: check for changes
        run: git status
      
      - name: stage changed files
        run: git add .
      
      - name: commit changed files
        run: git commit -m "Auto updating Data"
      
      - name: fetch from master
        run: git fetch origin master
      
      - name: push code to master
        run: git push origin master
